# Black formatting
[tool.black]
line-length = 79
include = '\.pyi?$'
extend-exclude = '''
/(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \venv
    | _build
    | buck-out
    | build
    | dist
    | (notebooks)
  )/
'''

# iSort
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
skip_gitignore = true
virtual_env = "venv"
balanced_wrapping = true
skip_glob = ["notebooks/*"]

# nbqa
[tool.nbqa.exclude]
flake8 = ""

[tool.nbqa.addopts]
black = [
	"--preview"
]